trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'diccraft'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: 'diccraft.zip'
    replaceExistingArchive: true

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'diccraft.zip'
    publishLocation: 'pipeline'